### ISSUE TITLE
epic store launch game into black full screen

### ISSUE THREAD

**Issue by qundus** [bottlesdevs/programs#143]
## Background
This issue is related to [this one][1] where i couldn't even launch the game.

## Describe The Issue
i'm trying to launch rocket league through Bottles epic games installer but the game goes back to the installer screen after launching a black full screen window.

## Expected Behavior 
the game should launch through epic game launcher into full screen or windowed mode.

## Logs
my bottle's configs
```yaml
Arch: win64
Creation_Date: '2022-10-02 22:00:06.102742'
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-1.10.3
Environment: Gaming
Environment_Variables:
    WINDOWED: '1'
External_Programs:
    ad4cbab5-c0a5-486b-afc6-2a7525dafa53:
        arguments: -opengl -SkipBuildPatchPrereq
        executable: EpicGamesLauncher.exe
        id: ad4cbab5-c0a5-486b-afc6-2a7525dafa53
        name: Epic Games Store
        path: C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win32\EpicGamesLauncher.exe
Installed_Dependencies:
- d3dx9
- msls31
- arial32
- times32
- courie32
- d3dcompiler_43
- d3dcompiler_47
- riched20
- andale32
- arialb32
- comic32
- georgi32
- impact32
- tahoma32
- trebuc32
- verdan32
- webdin32
- allfonts
- vcredist2015
Language: sys
LatencyFleX: latencyflex-v0.1.0
Latest_Executables: []
NVAPI: dxvk-nvapi-v0.5.4
Name: win-games
Parameters:
    custom_dpi: 96
    discrete_gpu: true
    dxvk: true
    dxvk_nvapi: false
    fixme_logs: false
    fsr: false
    fsr_level: 5
    fullscreen_capture: false
    gamemode: false
    gamescope: false
    gamescope_borderless: false
    gamescope_fps: 0
    gamescope_fps_no_focus: 0
    gamescope_fullscreen: true
    gamescope_game_height: 0
    gamescope_game_width: 0
    gamescope_scaling: false
    gamescope_window_height: 0
    gamescope_window_width: 0
    latencyflex: false
    mangohud: false
    mouse_warp: true
    obsvkc: false
    pulseaudio_latency: true
    renderer: gl
    sandbox: false
    sync: fsync
    take_focus: false
    use_be_runtime: true
    use_eac_runtime: true
    use_runtime: false
    use_steam_runtime: false
    versioning_automatic: false
    versioning_compression: false
    versioning_exclusion_patterns: false
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkbasalt: false
    vkd3d: true
    vmtouch: false
    vmtouch_cache_cwd: false
Path: win-games
Runner: lutris-7.2-2
Sandbox:
    share_net: true
    share_sound: true
State: 0
Uninstallers: {}
Update_Date: '2022-10-03 00:12:12.565088'
VKD3D: vkd3d-proton-2.6-1-5b73139
Versioning: false
Versioning_Exclusion_Patterns: []
Windows: win10
WorkingDir: ''
```

system info
```yaml
OS: Artix Linux x86_64 
Host: Dell G15 5515 1.7.1 
Kernel: 5.19.12-artix1-1 
Uptime: 4 hours, 34 mins 
Packages: 1225 (pacman), 19 (flatpak) 
Shell: bash 5.1.16 
Resolution: 1920x1080, 1920x1080 
DE: Cinnamon 5.4.12 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Apricity Icons [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 5 5600H with Radeon Graphics (12) @ 3.300GHz 
GPU: AMD ATI 05:00.0 Cezanne 
GPU: NVIDIA GeForce RTX 3050 Mobile 
Memory: 4042MiB / 7291MiB 
```

[1]: https://forum.usebottles.com/t/how-to-fix-epic-games-store-not-launching-games/602?u=neod3v
