### ISSUE TITLE
[Installers] Step for "run command"?

### ISSUE THREAD

**Issue by fosspill** [bottlesdevs/programs#24]
I'm currently playing around with the installer scripts and sorely miss a step to run a script.
I imagine installers being really handy when apps have weird dependencies or are tricky to get running, so being able to run some script to for instance modify configuration files within the game would be incredibly handy.

Sorry if this is already in the pipeline!

**Comment by mirkobrombin** [comment]
Hi, this was already scheduled (at least in my mind :D). Planning for 2022.1.14.


I'll use this issue to take some notes:
- every script should have access to some placeholders:
  - $BOTTLE_DIR
  - $TEMP_DIR
- cwd should be set to the bottle path
- scripts should not have access to curl/wget, better using the installer actions to register downloads with hash for corruption check

**Comment by fosspill** [comment]
Ah, sweet. I'll be writing some scripts once it arrives!

I completely agree with your points so far.

Maybe consider if other commands should be controlled by Bottles too? Either for security or convenience purposes.

An action for "write_to_file" for instance may be nicer looking than having a script which echos text into a file?

**Comment by mirkobrombin** [comment]
Yes definitely, I should be able to work on this in the next days, if you think of other actions that should implemented to replace some scripts let me know

**Comment by mirkobrombin** [comment]
Action `run_script` implemented here: https://github.com/bottlesdevs/Bottles/commit/fd5ceb4d48127d245a02866ded988fb73820b9ee

Usage:
```yaml
Name: test
Description: Testing scripts
Grade: Gold

Dependencies: []

Parameters: {}
  
Executable:
  name: Test
  file: EpicGamesLauncher.exe
  path: Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32
  arguments: -opengl -SkipBuildPatchPrereq
  
Steps:
- action: run_script
  script: |
    echo "Bottle is: !bottle_name"
    echo "Bottle path:"
    ls !bottle_path
    echo "Bottle drive_c:"
    ls !bottle_drive
```

Placeholders:
- `!bottle_name` -> display the bottle name
- `!bottle_path` -> point to the bottle root
- `!bottle_drive` -> point to the bottle `/drive_c`

Preventions:
- if `bottle.yml` is found in script, the installation will fail (should not be changed by scripts, btw no need for better preventions as every installer must be approved)

![image](https://user-images.githubusercontent.com/9479903/148458914-fc274aea-1b27-46e7-88b0-1b77dca46c35.png)

I will also provide actions like `download_archive`, `extract_archive`, `get_from_cab`, .. and others already seen for dependencies, but should only be used for specific program context, as if other programs can take benefits from these should be better to just make a dependency and declare in the manifest installer.
