### ISSUE TITLE
Epic Games Store won't launch after installation.

### ISSUE THREAD

**Issue by benedekmeszaros** [bottlesdevs/programs#314]
Hi, I'm using Linux mint 21.3, and trying to install **Epic Games Store** via bottles.
Wine is also installed.
Device:
```
OS: Linux Mint 21.3 Cinnamon
Cinnamon Version: 6.0.4
Linux Kernel: 6.5.11
CPU: 13th Gen Intel© Core™ i7-13620H × 10
GPU: NVIDIA RTX 4050
Memory: 32GB
```

After installation the application stop running, and barely provide any information what is the cause of it. Any body have any idea or how can I get deeper debugging?

Mainfest:
```
Name: epicgamestore
Description: The official Epic Games launcher.
Grade: Platinum
Arch: win64

Dependencies:
- d3dx9
- msls31
- riched20
- allfonts
- d3dcompiler_43
- d3dcompiler_47
- vcredist2015
- mono

Parameters:
  dxvk: true
  sync: fsync
  discrete_gpu: true
  
Executable:
  name: Epic Games Store
  icon: epicgamestore.svg
  file: EpicGamesLauncher.exe
  path: Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe
  arguments: -opengl -SkipBuildPatchPrereq
  
Steps:
- action: install_msi
  file_name: EpicGamesLauncherInstaller.msi
  url: https://proxy.usebottles.com/redistributable/programs/EpicGamesLauncherInstaller.msi
  file_checksum: False
  arguments: /q

Checks:
  files:
    - Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe
```

The only log information bottles provide:
```
fsync: up and running.
00d8:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
02a4:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
```
