### ISSUE TITLE
Folder Suggestion Structure

### ISSUE THREAD

**Issue by QuinsZouls** [bottlesdevs/programs#4]
Put all programs and games in the same folder (like /Programs/) and create a new folder inside of this path to store all asset of each program (/Programs/steam/, /Programs/epicgames/), each program folder must have a /assets/ folder to store icons and others files.
#
In the root of the folder must have a Info.yml file which includes all configurations with two new fields: 

- Category (to identify what type of program is, like Game, Audio, Productivity, etc...) 
- Version (the current version of the program)
```yml
Name: amazonmusic
Description: The official Amazon Music Desktop app.
Category: Audio
Version: 1.0.02.3.4
Grade: Silver

```

I think that this way is more efficient and allows store additional scripts and assets to run a program  (like a Prelaunch script of lutris)
